from os import getenv

API_HASH = getenv("API_HASH")
API_ID = getenv("API_ID")
MONGO_URI = getenv("MONGO_URI")
SESSION = getenv("SESSION")
GOOGLE_CX_ID = getenv("GOOGLE_CX_ID")
GOOGLE_DEV_API = getenv("GOOGLE_DEV_API")
SCREENSHOT_API = getenv("SCREENSHOT_API")
WOLFRAM_API = getenv("WOLFRAM_API")
GEMINI_1PSID = getenv("GEMINI_1PSID")
GEMINI_1PSIDTS = getenv("GEMINI_1PSIDTS")
OPENROUTER_COOKIE = getenv("OPENROUTER_COOKIE")
CHATGPT_BEARER_KEY = getenv("CHATGPT_BEARER_KEY")